    python -u run_longExp.py \
    --data ETTm1 \
    --root_path ./dataset/ETT-small \
    --data_path ETTm1.csv \
    --enc_in 7 \
    --seq_len 720 \
    --pred_len 96 \
    --e_layers 3 \
    --d_model 64 \
    --dropout 0.1 \
    --patch_len 24 \
    --stride 24 \
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --pad_size 1 \
    --local_size 2\
    --use_multi_gpu \
    --devices 0

    python -u run_longExp.py \
    --data ETTm1 \
    --root_path ./dataset/ETT-small \
    --data_path ETTm1.csv \
    --enc_in 7 \
    --seq_len 720 \
    --pred_len 192 \
    --e_layers 3 \
    --d_model 64 \
    --dropout 0.1 \
    --patch_len 24 \
    --stride 24 \
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --pad_size 1 \
    --local_size 2 \
    --use_multi_gpu \
    --devices 0

    python -u run_longExp.py \
    --data ETTm1 \
    --root_path ./dataset/ETT-small \
    --data_path ETTm1.csv \
    --enc_in 7 \
    --seq_len 720 \
    --pred_len 336 \
    --e_layers 3 \
    --d_model 64 \
    --dropout 0.2 \
    --patch_len 24 \
    --stride 24 \
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --pad_size 1 \
    --local_size 2\
    --use_multi_gpu \
    --devices 0

    python -u run_longExp.py \
    --data ETTm1 \
    --root_path ./dataset/ETT-small \
    --data_path ETTm1.csv \
    --enc_in 7 \
    --seq_len 720 \
    --pred_len 720 \
    --e_layers 3 \
    --d_model 128 \
    --dropout 0.1 \
    --patch_len 24 \
    --stride 24 \
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --pad_size 1 \
    --local_size 2\
    --use_multi_gpu \
    --devices 0