    python -u run_longExp.py \
    --data custom \
    --root_path ./dataset/weather \
    --data_path weather.csv \
    --enc_in 21 \
    --seq_len 720 \
    --pred_len 96 \
    --e_layers 2 \
    --d_model 256 \
    --dropout 0.2 \
    --patch_len 24 \
    --stride 24 \
    --pad_size 3 \
    --local_size 2\
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --use_multi_gpu \
    --devices 0,1

    python -u run_longExp.py \
    --data custom \
    --root_path ./dataset/weather \
    --data_path weather.csv \
    --enc_in 21 \
    --seq_len 720 \
    --pred_len 192 \
    --e_layers 3 \
    --d_model 256 \
    --dropout 0.2 \
    --patch_len 24 \
    --stride 24 \
    --pad_size 3 \
    --local_size 2\
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --use_multi_gpu \
    --devices 0,1
    python -u run_longExp.py \
    --data custom \
    --root_path ./dataset/weather \
    --data_path weather.csv \
    --enc_in 21 \
    --seq_len 720 \
    --pred_len 336 \
    --e_layers 2 \
    --d_model 128 \
    --dropout 0.2 \
    --patch_len 24 \
    --stride 24 \
    --pad_size 3 \
    --local_size 2\
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --use_multi_gpu \
    --devices 0,1

    python -u run_longExp.py \
    --data custom \
    --root_path ./dataset/weather \
    --data_path weather.csv \
    --enc_in 21 \
    --seq_len 720 \
    --pred_len 720 \
    --e_layers 3 \
    --d_model 64 \
    --dropout 0.2 \
    --patch_len 24 \
    --stride 24 \
    --pad_size 3 \
    --local_size 2\
    --batch_size 1024 \
    --patience 20 \
    --learning_rate 0.001 \
    --use_multi_gpu \
    --devices 0,1